---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
     runs-on: ubuntu-latest

     steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      -
        name: Train model
        run: python src/train.py

      -
        name: Validate model
        run: python src/test.py

      -
        name: Run unit and e2e tests
        run: python -m pytest tests/

      -
        name: Login to Docker Hub
        if: "github.ref == 'refs/heads/main'"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push Docker image
        if: "github.ref == 'refs/heads/main'"
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cnn-mnist:latest
          context: .
          file: ./Dockerfile

      -
        name: Login to GitHub Container Registry
        if: "github.ref == 'refs/heads/main'"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push to GHCR
        if: "github.ref == 'refs/heads/main'"
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/mnist-cnn-classifier:latest
          context: .
          file: ./Dockerfile
